name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      # Step 1: Check out the repository
      - name: Get files
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Change to the 'my-app' directory
      - name: Change directory to my-app
        working-directory: ./my-app
        run: echo "Changed directory to my-app"

      # Step 4: Install packages
      - name: Install packages
        working-directory: ./my-app
        run: npm ci

      # Step 5: Build the project
      - name: Build project
        working-directory: ./my-app
        run: npm run build

      # Step 6: Export static files
      - name: Export static files
        working-directory: ./my-app
        run: npm run export

      # Step 7: Add .nojekyll file
      - name: Add .nojekyll file
        working-directory: ./my-app/out
        run: touch .nojekyll

      # Step 8: Deploy to GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: my-app/out
